services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'bot'
    restart: unless-stopped
    networks:
      - bot-network
    volumes:
      - ./logs:/src/logs/
    env_file:
      - ./app/.env

networks:
  bot-network:
    driver: bridge
