services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'bot'
    restart: unless-stopped
    networks:
      - bot-network
    volumes:
      - ./logs:/src/logs/

networks:
  bot-network:
    driver: bridge
