[tool.poetry]
name = "bot-chatgpt-api"
version = "0.1.0"
description = "Bot for interaction with ChatGPT API"
authors = ["a.merkulov <merk.aimerk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.17.0"
pydantic-settings = "^2.7.1"
openai = "^1.60.0"
cachetools = "^5.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
