name: Deploy bot to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy process telegram bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/bot

            if [ ! -d "bot-chatgpt-api/.git" ]; then
              git clone https://github.com/aimerkz/bot-chatgpt-api.git
            else
              cd bot-chatgpt-api/ && git pull origin master
            fi
            
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> ./app/.env
            echo "API_KEY=${{ secrets.API_KEY }}" >> ./app/.env
            echo "BOT_ENV=${{ secrets.BOT_ENV }}" >> ./app/.env

            docker compose down --rmi all
            docker compose up -d --build
