name: Types check with pyright

on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    name: Run pyright check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          project: "./pyproject.toml"
