name: Pytest

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true

      - name: Install pytest-md and pytest-emoji
        run: uv add --dev pytest-md pytest-emoji

      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          report-title: 'Pytest Report'
          click-to-expand: true
          emoji: true
          job-summary: true
          verbose: true
          custom-arguments: '-c pyproject.toml'
