name: Pytest

on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Install pytest-md and pytest-emoji
        run: poetry add --group dev pytest-md pytest-emoji

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          report-title: 'Test Report'
          click-to-expand: true
          emoji: true
          job-summary: true
          verbose: true
          custom-arguments: '-c pyproject.toml'
